// Package supervisor runs one managed Pando instance for one repository, as
// ADR-039 (option C) describes: `gintrack serve` starts an instance for each
// repository that opted in to semantic search, keeps it healthy and stops it on
// exit.
//
// It is a native-only package next to internal/pando. It uses os/exec and file
// locks, so it can never live in internal/core, and it imports neither
// internal/core nor internal/config: a Supervisor is built from a plain Options
// struct, and the code that reads the configuration file (GIT-US-0174) and the
// code that wires instances into `gintrack serve` (GIT-US-0175) fill that struct
// in. The Options carry no maxInstances: capping the number of instances is the
// caller's job, one Supervisor per repository.
//
// # Where things live
//
// Everything is under <CacheDir>/pando/<key>/ (mode 0700), where key is
// InstanceKey(RepoRoot): SanitizeProjectID of the root plus a short hash of the
// absolute path, so two clones cannot collide.
//
//	.pando.toml       0600  generated, rewritten on every child start
//	token             0600  the instance's bearer token, generated by Start
//	state.json        0600  Status, rewritten atomically on every change
//	supervisor.lock         flock held while a Supervisor owns the directory
//	pando.log               stdout and stderr of the child, token redacted,
//	                        rotated at 10 MB with 2 rotated files kept
//	data/                   Pando's database (derived, safe to delete)
//	.pando/ipc.lock         Pando's own lock, created because the child's
//	                        working directory is the instance directory
//
// Nothing is ever written inside the repository: the child runs with the
// instance directory as its working directory (and `--cwd`) and with
// PANDO_CONFIG_PARENT_SEARCH=false, so the generated .pando.toml is the only
// local configuration it reads. The user's global Pando file still supplies
// model providers and API keys, which are never copied.
//
// # Lifecycle
//
// Start takes the per-instance lock without blocking (ErrLocked means another
// gintrack process supervises the instance: connect to it through ReadStatus
// and ReadToken instead), checks `pando --version` against Options.MinVersion,
// writes the token file and launches the supervision goroutine, then returns.
// It never waits for the child to become ready. Before starting it ends an
// orphan: a child that state.json records, that is still alive although its
// supervisor is dead, and whose command line names the instance directory.
//
// Each child run:
//
//  1. picks a free loopback port by binding 127.0.0.1:0 (or inside
//     [PortMin, PortMax]) and releasing it, and writes .pando.toml;
//  2. runs `pando mcp-server --no-stdio --cwd <dir>` in its own process group;
//     on Linux it also sets Pdeathsig = SIGTERM, so the child dies with the
//     supervisor, and the supervision goroutine is locked to its OS thread for
//     that reason (Pdeathsig fires when the thread that started the child ends).
//     Where there is no Pdeathsig (macOS) the child runs under Options.Watchdog,
//     `gintrack __pando-watch`, which ends the child's group when the lifeline
//     pipe to the supervisor closes, SIGKILL included (RunWatchdog);
//  3. is ready when pando.Client.Health succeeds with our token on our port
//     within ReadyTimeout. Pando silently moves to another port when the
//     requested one is busy, and a 401 means someone else owns it: both look
//     like an unreachable endpoint, so the child is killed and the run counts as
//     a crash, and the next run picks a new port;
//  4. is health-checked every HealthInterval afterwards; HealthFailures
//     consecutive failures kill the child and count as a crash.
//
// Crashes restart with exponential backoff (BackoffMin doubling up to
// BackoffMax, by the number of crashes still inside CrashWindow). MaxCrashes
// crashes inside CrashWindow mark the instance failed: it is not retried until
// Restart. Restart also bounces a running child without counting a crash.
// Stop sends SIGTERM to the process group, waits StopTimeout, then SIGKILL.
//
// The instance dies with the supervisor (ADR-039 open question 1, default) and
// is reached over loopback HTTP (open question 2, default). The port changes on
// every child start and is never reused on purpose; clients resolve it through
// state.json.
//
// # AG-UI instances
//
// Options.Kind = KindAGUI runs `pando agui-serve --cwd <dir> --host 127.0.0.1 --port N
// --no-tls --token-file <dir>/token` instead (GIT-US-0185), for the agent panel of ADR-035. It
// lives in <CacheDir>/pando/<AGUIKey>/ (InstanceKey plus "-agui"), so it has its own lock, state
// file, token, log and data directory and runs beside the repository's MCP instance. Everything
// in Lifecycle applies unchanged; what differs is the configuration, which the caller renders
// (Options.Files, called on every start with the chosen port), and the health check: GET
// <AGUIPath>/healthz, and on the first check also /info with the bearer token, which is what
// tells our child from another process that holds the port. Status.AGUIURL replaces MCPURL, and
// Endpoint returns it.
//
// # Windows
//
// The package compiles on Windows, but managed mode is not supported there yet
// (ADR-039 open question 5): the lock is a create-exclusive file that a crash
// leaves behind, and there is no Job Object tying the child's lifetime to the
// supervisor.
package supervisor
